Remove jQuery dependency
freeCodeCamp/boilerplate-project-stockchecker pull request #16
Opened 2021-04-29 01:19 UTC by santi224m

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes [#41355](https://github.com/freeCodeCamp/freeCodeCamp/issues/41355) on freeCodeCamp/freeCodeCamp repository.

This replaces jQuery with a JavaScript file so that when users set the content security policies to only allow files from the same server, it won't break the page.
It also moves page styling from the html file to a css file.

2021-04-29 12:38 UTC, gikf reviewed
I've tested this on fresh boilerplate copy and it seemed fine.

Could you change the indentations to use two spaces per level?

I'm a bit confused with code formatting of couple `<code>` tags, placing angle brackets on different line, but I'm gonna refer to other's opinion regarding that.

2021-04-29 20:56 UTC, santi224m commented
I changed the indentations to two spaces on the three files and I also fixed the formatting on the code tags. Let me know if you want me to change anything else.

2021-05-01 13:42 UTC, gikf requested changes
Thanks for the update @santi224m.

Just one more, small suggestion and I think I'd be okay with the rest.

2021-05-01 13:42 UTC, gikf commented on views/index.html
>      <!-- Your web-app is https, so your scripts need to be too -->
```suggestion
```

2021-05-02 01:35 UTC, santi224m commented
@gikf I removed the comment, I think it should all be good now

2021-05-02 05:45 UTC, gikf approved these changes
LGTM :+1:

2021-05-02 08:23 UTC, merged